fixtures:
  symlinks:
    "patchmgmt": "#{source_dir}"
  repositories:
    "oski":
      repo: "git://github.com/arusso/puppet-oski"
      ref: "0.0.1"
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "2.6.0"
